FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# 기본 유틸 설치
RUN apt update && apt install -y python3-dev python3-pip git ffmpeg libsm6 libxext6

# 작업 디렉토리
WORKDIR /workspace

# requirements 복사
COPY requirements.txt /workspace/requirements.txt

# pip 업그레이드
RUN pip install --upgrade pip

# requirements 설치
RUN pip install -r requirements.txt

# 소스 복사
COPY . /workspace

# 엔트리포인트
ENTRYPOINT ["python", "train.py"]
